name: Build, Test and update Documentaion

on:
    pull_request:
        branches:
            - main
            - dev

env:
    DOTNET_VERSION: "7.0.x"
    PROJECT_PATH: "UnitService.Core/UnitService.Core.csproj"
    TEST_PROJECT_PATH: "UnitService.Test/UnitService.Test.csproj"

jobs:
    build-and-test:
        name: Build-and-test PR on ${{matrix.os}}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Install dependencies
              run: dotnet restore ${{env.PROJECT_PATH}}

            - name: Build library
              run: dotnet build ${{env.PROJECT_PATH}} --configuration Release --no-restore

            - name: Run unit tests
              run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults --no-build

            - name: Upload Test Results
              uses: actions/upload-artifact@v2
              with:
                  name: Test Results
                  path: ./TestResults/*.trx

            - name: Copy XML documentation
              run: copy UnitService.Core/obj/Release/netstandard2.1/UnitService.Core.xml /docs

            - name: Upload documentation
              uses: actions/upload-artifact@v2
              with:
                  name: documentation
                  path: /docs
